# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 11:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('30cm', '30 CM'), ('40cm', '40 CM'), ('50cm', '50 CM'), ('55cm', '55 CM')], max_length=50), default=[], size=None),
            preserve_default=False,
        ),
    ]
